### ISSUE TITLE
PointsAtMe function on Expanded Particles

### ISSUE THREAD

**Issue by WayanKita** [SOPSLab/AmoebotSim#32]
**Description**
In the pulldemo.ccp, I would expect the following statement to return true if nbr moveDir is pointing at the leader:
pointsAtMe(nbr, nbr.moveDir)
This is sometimes not the case. I have noticed that pointsAtMe(nbr, nbr.moveDir) noes not work as intended when nbr is expanded.

**To Reproduce**
1. Run pulldemo.ccp
2. add this code before the pull:
if(isHeadLabel(nbrLabel)){
    nbrLabel=(nbrLabel+1)%10;
}
This ensures that the follower only gets pulled into the tail of the leader.
3. Log after the pull the outcome of pointsAtMe(nbr, nbr.moveDir)
4. when observing the GUI we see that the follower always points at the leader but pointsAtMe(nbr, nbr.moveDir) will sometimes return false

**Expected Behavior**
pointsAtMe(nbr, nbr.moveDir) should always return true for the above-mentioned case.

**Platform**
Qt 5.14.1 (i386-little_endian-ilp32 shared (dynamic) release build; by MSVC 2017) on "windows" 
OS: Windows 10 Version 1909 [winnt version 10.0.18363]

**Comment by jdaymude** [comment]
Hi @WayanKita, apologies it took quite some time to get to this. I've reviewed your [video](https://www.youtube.com/watch?v=Hn7q2Irem8M) and after looking into this I've concluded that this is not a bug, but a misunderstanding of the way labels and directions work. As this is a confusing topic, I've used your example in a new demo tutorial to hopefully clear things up.

As you noticed in your code, there is nothing wrong with the actual `pointsAtMe()` functionality under the hood; the leader always pulls the follower successfully. Where you get unexpected behavior is the `headMarkDir` visualization, which you observe to not always point at the leader. The problem with this is your `moveExpandDir % 6` call. There is no reason why an expanded label `lbl` (which is 0-9) and `lbl % 6` should point in the same direction, and this is exactly what you're observing.

If you'd like to see how a follower-to-leader pointer can be maintained even with expansions and pull/push handovers, take a look at the new [BallroomDemo tutorial](https://amoebotsim.readthedocs.io/en/latest/tutorials/tutorials.html#ballroomdemo-working-together) in our docs.
